### ISSUE TITLE
Quick review

### ISSUE THREAD

**Issue by Helias** [QD-2022/Welcome-Bot#37]
Ho dato un'occhiata veloce, **appena posso eseguo i progetti in locale.**
Sembra che avete usato i conventional, creato e commentato le PRs, mi sembra tutto molto completo dall'esterno.
Inoltre, il numero di commits fa capire che nonostante abbiate finito "presto", avete lavorato tanto, mi fa piacere.

Ottimo anche l'uso dei test parametrizzati 👍 , bravi 🚀

**Comment by domenicoblanco** [comment]
Grazie!
