### ISSUE TITLE
Define welcome messages

### ISSUE THREAD

**Issue by domenicoblanco** [QD-2022/Welcome-Bot#4]
The bot should answer with a random answers from a pre-defined array of answers

To do:

- [x] Generate an English only array of answers
- [x] Generate an Italian only array of answers
- [x] Use a JSON to store & load data dynamically

**Comment by domenicoblanco** [comment]
As seen in previous tests, the update returned only some basic infos about the new user.
We need to dig more to found something to retrieve complete user informations

**Comment by Valeri0p** [comment]
There are only 3 entries per language right now, but we met all the requirements.
